name: buzz
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  at_client_mobile: ^3.1.18
  at_contact: ^3.0.7
  # at_location_flutter: ^3.1.6
  at_onboarding_flutter: ^4.0.4
  bitsdojo_window: ^0.1.2
  cached_memory_image: ^1.3.1
  cupertino_icons: ^1.0.5
  desktop_drop: ^0.3.3
  dotted_border: ^2.0.0+2
  file_picker: ^4.6.1
  file_selector: ^0.8.4+3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.6.1
  freezed_annotation: ^2.0.3
  google_fonts: ^3.0.1
  image: ^3.2.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  page_transition: ^2.0.5
  path_provider: ^2.0.11
  provider: ^6.0.3
  share_plus: ^4.0.7
  shared_preferences: ^2.0.15
  simple_animations: ^4.1.0
  tabler_icons: ^0.0.3
  url_launcher: ^6.1.3
  zxing2: ^0.1.0

dependency_overrides:
  permission_handler: ^10.0.0
  at_persistence_secondary_server: ^3.0.28
  file_saver:
    git:
      url: https://github.com/incrediblezayed/file_saver
      ref: main

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  import_sorter: ^4.6.0
  json_serializable: ^6.2.0
  lints: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/avatars/
    - assets/images/flags/
    - assets/lottie/
    - .env

flutter_icons:
  image_path: "assets/images/@buzz_logo.png"
  adaptive_icon_background: "#FFFFFF"
  image_path_ios: "assets/images/@buzz_logo.png"
  image_path_android: "assets/images/@buzz_logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

import_sorter:
  emojis: true
